version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
        - "27017:27017"
    volumes:
          - ./mongo-database:/mongo-database


  webapp:
    build: .
    container_name: webapp
    environment:
          SPRING_DATA_MONGODB_HOST: mongo
          SPRING_DATA_MONGODB_PORT: 27017
          SPRING_DATA_MONGODB_DATABASE: testbot
          SPRING_DATA_MONGODB_USERNAME: admin
          SPRING_DATA_MONGODB_PASSWORD: 12345678
    ports:
      - 8080:8080
    depends_on:
      - mongodb
